apiVersion: v1
kind: Pod
metadata:
  name: ueransim-sst-1
  namespace: oai
spec:
  containers:
    - name: ueransim-container
      image: docker.io/maitaba/ueransim:v3.2.6
      command: [ "tail", "-f", "/dev/null" ]
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
        privileged: true
      volumeMounts:
        - name: ueransim-volume
          mountPath: /data
        - name: dev-net-tun
          mountPath: /dev/net/tun
          readOnly: false
  volumes:
    - name: ueransim-volume
      emptyDir: {}
    - name: dev-net-tun
      hostPath:
        path: /dev/net/tun
        type: CharDevice
