############# Common configuration

# Log level for all the NFs
log_level:
  general: info

# If you enable registration, the other NFs will use the NRF discovery mechanism
register_nf:
  general: yes

http_version: 2
curl_timeout: 6000 #milliseconds can be changed if the network have issues

## general single_nssai configuration
## Defines YAML anchors, which are reused in the config file
snssais:
  - &embb_slice1
    sst: 1
  - &embb_slice2
    sst: 128
  - &embb_slice3
    sst: 130

############## SBI Interfaces
### Each NF takes its local SBI interfaces and remote interfaces from here, unless it gets them using NRF discovery mechanisms
nfs:
  amf:
    host: oai-amf
    sbi:
      port: 80
      api_version: v1
      interface_name: eth0
    n2:
      interface_name: eth0
      port: 38412
  smf:
    host: oai-smf
    sbi:
      port: 8080
      api_version: v1
      interface_name: eth0
    n4:
      interface_name: eth0
      port: 8805
  smf2:
    host: oai-smf2
    sbi:
      port: 8081
      api_version: v1
      interface_name: eth0
    n4:
      interface_name: eth0
      port: 8806
  smf3:
    host: oai-smf3
    sbi:
      port: 8082
      api_version: v1
      interface_name: eth0
    n4:
      interface_name: eth0
      port: 8807
  lmf:
    host: oai-lmf
    sbi:
      port: 80
      api_version: v1
      interface_name: eth0
  upf:
    host: oai-upf
    sbi:
      port: 80
      api_version: v1
      interface_name: eth0
    n3:
      interface_name: eth0
      port: 2152
    n4:
      interface_name: eth0
      port: 8805
    n6:
      interface_name: eth0
    n9:
      interface_name: eth0
      port: 2152
  upf2:
    host: oai-upf2
    sbi:
      port: 80
      api_version: v1
      interface_name: eth0
    n3:
      interface_name: eth0
      port: 2152
    n4:
      interface_name: eth0
      port: 8806
    n6:
      interface_name: eth0
    n9:
      interface_name: eth0
      port: 2152
  upf3:
    host: oai-upf3
    sbi:
      port: 80
      api_version: v1
      interface_name: eth0
    n3:
      interface_name: eth0
      port: 2152
    n4:
      interface_name: eth0
      port: 8807
    n6:
      interface_name: eth0
    n9:
      interface_name: eth0
      port: 2152
  udm:
    host: oai-udm
    sbi:
      port: 80
      api_version: v1
      interface_name: eth0
  udr:
    host: oai-udr
    sbi:
      port: 80
      api_version: v1
      interface_name: eth0
  ausf:
    host: oai-ausf
    sbi:
      port: 80
      api_version: v1
      interface_name: eth0
  nrf:
    host: oai-nrf
    sbi:
      port: 80
      api_version: v1
      interface_name: eth0
  nssf:
    host: oai-nssf
    sbi:
      port: 80
      api_version: v1
      interface_name: eth0
#### Common for UDR and AMF
database:
  host: mysql
  user: test
  type: mysql
  password: test
  database_name: oai_db
  generate_random: true
  connection_timeout: 300 # seconds

## DNN configuration
dnns:
  - dnn: "oai"
    pdu_session_type: "IPV4"
    ipv4_subnet: "12.1.1.0/24"
  - dnn: "oai2"
    pdu_session_type: "IPV4"
    ipv4_subnet: "12.1.2.0/24"
  - dnn: "oai3"
    pdu_session_type: "IPV4"
    ipv4_subnet: "12.1.3.0/24"
