# Reference:- TS 29.531 R16.0.0., Section- 6.1.6 Data Model 
info:
  version: 2.0.0
  description: OAI-NSSF Release v2.1.0
configuration:
  nsiInfoList:
    - snssai:
        sst: 1
      nsiInformationList:
        nrfId: http://oai-nrf:80/nnrf-disc/v1/nf-instances
        nsiId: '11'
    - snssai:
        sst: 128
      nsiInformationList:
        nrfId: http://oai-nrf:80/nnrf-disc/v1/nf-instances
        nsiId: '12'
    - snssai:
        sst: 130
      nsiInformationList:
        nrfId: http://oai-nrf2:80/nnrf-disc/v1/nf-instances
        nsiId: '12'
  taInfoList:
    - tai:
        plmnId:
          mcc: '001'
          mnc: '01'
        tac: '0x0001'
      supportedSnssaiList:
      - sst: 1
      - sst: 128
      - sst: 130
  amfInfoList:
    - targetAmfSet: 001-01-128-01
      nrfAmfSet: http://oai-cn5g-nrf.fr:80/nnrf-disc/v1/nf-instances
      nrfAmfSetNfMgtUri: http://oai-cn5g-nrf.fr:80/nnrf-nfm/v1/nf-instances
      amfList:
        - nfId: 405e8251-cc5a-45dd-a494-efb9eaf1cd58
          supportedNssaiAvailabilityData:
              tai:
                plmnId:
                  mcc: 001
                  mnc: 01
                tac: 0x0001
              supportedSnssaiList:
                - sst: 1
                - sst: 128
                - sst: 130


